const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "false" || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "false" || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/suhailmd-2.0";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/bH1kbX0/a4c0b1af253197d4837ff6760d5b81c0.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "© SuhailTechInfo" 


global.devs = "" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923444844060,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com/" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_00_04_12_28_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDEzLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTg5LFxuICAgICAgICAzOSxcbiAgICAgICAgNzIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMzYsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjUwLFxuICAgICAgICAxNzMsXG4gICAgICAgIDQxLFxuICAgICAgICA1MyxcbiAgICAgICAgNDcsXG4gICAgICAgIDk4LFxuICAgICAgICAyNDksXG4gICAgICAgIDE1MCxcbiAgICAgICAgNDAsXG4gICAgICAgIDUzLFxuICAgICAgICAxMjAsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNDksXG4gICAgICAgIDc0LFxuICAgICAgICAxMDcsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjAyLFxuICAgICAgICAxMjQsXG4gICAgICAgIDczLFxuICAgICAgICAxNDMsXG4gICAgICAgIDk1LFxuICAgICAgICAxMjFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODIsXG4gICAgICAgIDIyLFxuICAgICAgICAyMTcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjAyLFxuICAgICAgICAxMTksXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjQyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTgsXG4gICAgICAgIDIyNCxcbiAgICAgICAgODMsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNTUsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTUwLFxuICAgICAgICAxMTYsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjksXG4gICAgICAgIDg4LFxuICAgICAgICA0MixcbiAgICAgICAgNjAsXG4gICAgICAgIDE4NixcbiAgICAgICAgODMsXG4gICAgICAgIDU3LFxuICAgICAgICAyMzAsXG4gICAgICAgIDExN1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDQxLFxuICAgICAgICAyOSxcbiAgICAgICAgMTYsXG4gICAgICAgIDY2LFxuICAgICAgICAzNixcbiAgICAgICAgMTEsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNDMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTAwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTM4LFxuICAgICAgICAxMjMsXG4gICAgICAgIDg5LFxuICAgICAgICA5NSxcbiAgICAgICAgMTc0LFxuICAgICAgICAyMTAsXG4gICAgICAgIDQ1LFxuICAgICAgICAxNixcbiAgICAgICAgMTg0LFxuICAgICAgICA0MCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTE5LFxuICAgICAgICA4NixcbiAgICAgICAgMTAsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTQsXG4gICAgICAgIDc3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1LFxuICAgICAgICAxMTUsXG4gICAgICAgIDUwLFxuICAgICAgICAyMTQsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTU0LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTUzLFxuICAgICAgICA5OCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNjIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMTUsXG4gICAgICAgIDM2LFxuICAgICAgICAxNzQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTUsXG4gICAgICAgIDg3LFxuICAgICAgICAxNSxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjksXG4gICAgICAgIDgyLFxuICAgICAgICAyNDIsXG4gICAgICAgIDE2MixcbiAgICAgICAgMjUyLFxuICAgICAgICAxNTUsXG4gICAgICAgIDE1MSxcbiAgICAgICAgNjZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2LFxuICAgICAgICAyNixcbiAgICAgICAgMjI0LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMzAsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjI2LFxuICAgICAgICA3NyxcbiAgICAgICAgMTIyLFxuICAgICAgICA4MixcbiAgICAgICAgMjA2LFxuICAgICAgICAyMzksXG4gICAgICAgIDIxNSxcbiAgICAgICAgODIsXG4gICAgICAgIDU2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDEyLFxuICAgICAgICAxNjMsXG4gICAgICAgIDE3NCxcbiAgICAgICAgNDcsXG4gICAgICAgIDk3LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTY3LFxuICAgICAgICAyNTIsXG4gICAgICAgIDIwLFxuICAgICAgICAwLFxuICAgICAgICA3OCxcbiAgICAgICAgMTMsXG4gICAgICAgIDU1LFxuICAgICAgICA2NFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4MCxcbiAgICAgICAgMSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNTksXG4gICAgICAgIDE4MyxcbiAgICAgICAgNSxcbiAgICAgICAgMTQyLFxuICAgICAgICAxNyxcbiAgICAgICAgOTgsXG4gICAgICAgIDk0LFxuICAgICAgICAzMSxcbiAgICAgICAgMjgsXG4gICAgICAgIDY3LFxuICAgICAgICAxNzEsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTA0LFxuICAgICAgICAxMzYsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAyNDksXG4gICAgICAgIDExMCxcbiAgICAgICAgNjMsXG4gICAgICAgIDE2LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzcsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTQzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDIzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICA1NixcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDExNVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA4NyxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA0NCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMTExXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI2LFxuICAgICAgICAyNDQsXG4gICAgICAgIDEwLFxuICAgICAgICA3NyxcbiAgICAgICAgMTMxLFxuICAgICAgICAxODMsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMixcbiAgICAgICAgMjA1LFxuICAgICAgICAzLFxuICAgICAgICAxNTQsXG4gICAgICAgIDU3LFxuICAgICAgICAxMjEsXG4gICAgICAgIDE1LFxuICAgICAgICAxNzIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjQ4LFxuICAgICAgICA5MixcbiAgICAgICAgMTMsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTE1LFxuICAgICAgICAyMTMsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTksXG4gICAgICAgIDE2NCxcbiAgICAgICAgODQsXG4gICAgICAgIDU1LFxuICAgICAgICAyMTMsXG4gICAgICAgIDE2OCxcbiAgICAgICAgNzcsXG4gICAgICAgIDQwLFxuICAgICAgICAxMzksXG4gICAgICAgIDIxNyxcbiAgICAgICAgNTYsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTIwLFxuICAgICAgICAxMDgsXG4gICAgICAgIDEyNixcbiAgICAgICAgODUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgOTIsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjE4LFxuICAgICAgICAxMTcsXG4gICAgICAgIDQwLFxuICAgICAgICAxMDQsXG4gICAgICAgIDIwLFxuICAgICAgICA4NSxcbiAgICAgICAgMTI5LFxuICAgICAgICA4OCxcbiAgICAgICAgODMsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNzIsXG4gICAgICAgIDIyNCxcbiAgICAgICAgNzQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTcsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTkyLFxuICAgICAgICA2OCxcbiAgICAgICAgNjUsXG4gICAgICAgIDM0LFxuICAgICAgICAxM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogNjgsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwieVA3SGljbCt0dEVENXJRWkdQVjlrUXBQbENLU2RibzdsZ29FMXVrSml0MD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyNjM3MTM3OTYyNDFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkFCMjM3ODA3REUzQjQ0MkU0RENCRjUxNzQ1RUUyNUNBXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTczNTM0NDIzN1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI2MzcxMzc5NjI0MUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNEQxQUMwRkNCOUQxQjQ4NEQ0NzRGMDVEOTgxMjNCODhcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzM1MzQ0MjM4XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiA2MSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiA2MSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIm9VY0k2bnlMU0FTY1hIMjBuUHJxWFFcIixcbiAgXCJwaG9uZUlkXCI6IFwiMTkzYWM4MzYtYjhiZS00NTg5LWE1NGEtMTFiZGRkNWY5MjgzXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI1NSxcbiAgICAgIDE3MixcbiAgICAgIDE2OSxcbiAgICAgIDg4LFxuICAgICAgMjQ2LFxuICAgICAgMjIxLFxuICAgICAgOTksXG4gICAgICAyMTMsXG4gICAgICAxODYsXG4gICAgICA4MixcbiAgICAgIDE2NSxcbiAgICAgIDEwNSxcbiAgICAgIDM0LFxuICAgICAgMTU3LFxuICAgICAgMzIsXG4gICAgICA0MixcbiAgICAgIDMyLFxuICAgICAgMTQ3LFxuICAgICAgMjM2LFxuICAgICAgMTRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE5MCxcbiAgICAgIDE1NCxcbiAgICAgIDE4OSxcbiAgICAgIDIxOSxcbiAgICAgIDM2LFxuICAgICAgMTA3LFxuICAgICAgNDcsXG4gICAgICAzOCxcbiAgICAgIDE3NixcbiAgICAgIDE4OCxcbiAgICAgIDIwNSxcbiAgICAgIDExNixcbiAgICAgIDUwLFxuICAgICAgMTQzLFxuICAgICAgNTgsXG4gICAgICAxOTYsXG4gICAgICAyNTIsXG4gICAgICAyMzgsXG4gICAgICAyMzUsXG4gICAgICAxODFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMZW5zckVGRU9lQXZic0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIm4rWGxlL1ZYZW1UK09PRGRlajVmNXJoN0ZaTzFVQnV0cGpyQWNjZXcxRGM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiMGFGZEI1SmhEcVg2TFZQeVg3VHI4SldlVFFLM0syakFUL1BweEJtVW5mM1pjMmJpSXd0QU95N2o1cjR6eGVhUUpnWDlLVDR5bEpQa0JJZEE3eFo0QkE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwieGxBMTNteVpoeXpkaDI0ZHNnMzVCNGpIbENuR3pFOGFGc2V3ME5YYXRsSTJJN0FzSGpkdXNUTlM3WktnREJtWXpGL3JnejVIbnRvZXk2ZWVDTlJwRFE9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNjM3MTM3OTYyNDE6MzZAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjY1MDczNjg3MDg1MzA5OjM2QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIk9UXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNjM3MTM3OTYyNDE6MzZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDU1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MzUzNDQyMzUsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFMR1hcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxHTy5qc29uIjogIntcImtleURhdGFcIjpcIjBqMHZWZVhSeGNtMXh5UkpMN0l5QWxLeDFRL205WVg2UVppM2VqY0VLbms9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ0NTc2MTk3MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEdQLmpzb24iOiAie1wia2V5RGF0YVwiOlwiWXlGYjkzbDRWSWh2amhzcEhxaW9tbGNKY2p0TWh6VSs1dE5YMzRzdFFvVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDQ1NzYxOTczLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxLDNdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxHUS5qc29uIjogIntcImtleURhdGFcIjpcIkREVk5tQUpKTCtGUXlvdEQvVGErbVEzVkFqZTErTFducGdST0sreTBmNGs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ0NTc2MTk3MyxcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsM119LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEdSLmpzb24iOiAie1wia2V5RGF0YVwiOlwiRmRRMkwvcUdZVlJIUWNVL2JMOC9HclRvSnIxejFSUkMxa3ZDaUo1aWxPWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDQ1NzYxOTczLFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwzLDVdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxHUy5qc29uIjogIntcImtleURhdGFcIjpcIm1zakNPMEpCcW84blpqczZDeGtlVmNrR3A2Z0hwVmZpN1JPU3ZOY2grc1U9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ0NTc2MTk3MyxcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEdULmpzb24iOiAie1wia2V5RGF0YVwiOlwiV3VPbVB3dEVMaXhpaG84UzlaaVVUT0dqZ091d1ZUVG5ZbTRFK2tOYmM1cz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDQ1NzYxOTczLFwiY3VycmVudEluZGV4XCI6NixcImRldmljZUluZGV4ZXNcIjpbMCw2XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMR1UuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJPZUFXQjB6OWhVNDM1ZEpCazF1b1JPa3J0aU1qdmJBaS8yRHQvd29HN2s4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE0NDU3NjE5NzMsXCJjdXJyZW50SW5kZXhcIjo2LFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MzUzNDE4OTA2NjhcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMR1YuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ3L0JJTlp0YUM1cm9DVVVSTm1vNlI1SHR0RTVKU2JaSzlYbW1sYk9mSElZPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE0NDU3NjE5NzQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxHVy5qc29uIjogIntcImtleURhdGFcIjpcImZTaFlqNEdOTllncFN3OFpvRGtSTnJBRHF6cmlUZDlocWpTdEc4MVBvbG89XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ0NTc2MTk3NCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTczNTM0NDIyNTcxOVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxHWC5qc29uIjogIntcImtleURhdGFcIjpcIjBjQkdxQ1lGRU4yZitNSkN0RmZxWS85TmhUelpRV3grMjYwZnBSek1veDA9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ0NTc2MTk3NSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzM1MzQ0MjM3NTQzXCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.0.1-developement-x",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Suhail-XMD",
  ownername:process.env.OWNER_NAME|| "Don",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "yepeTQaFk7r9ymusihgXYvdN",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "0cdb1aed858329b9793413672094ce0d";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
